desc "Upload IPA file and Send an email to single email"
lane :testSingleEmail do
  gym
  appbox(
    emails:'info@developerinsider.in'
  )
end


desc "Upload IPA file and Send email to multiple commas separated emails"
lane :testMultipleEmail do
  gym
  appbox(
    emails:'info@developerinsider.in,publisher@developerinsider.in'
  )
end


desc "Upload IPA file and Send email with a custom message."
lane :testEmailWithCustomMessage do
  gym
  appbox(
    emails:'info@developerinsider.in',
    message: "#{File.basename(lane_context[SharedValues::IPA_OUTPUT_PATH], '.ipa')} is ready to test.",
  )
end


desc "Upload IPA file and notify a Slack or Microsoft Teams channel."
lane :testWebhook do
  gym
  appbox(
    emails: 'info@developerinsider.in',
    slack_webhook_url: ENV['SLACK_WEBHOOK_URL'],
    # webhook_message is ignored by AppBox 4; the notification text comes from the build.
  )
end


desc "Upload IPA file and keep the same link for all future upload IPAs."
lane :testKeepSameLink do
  gym
  appbox(
    emails:'info@developerinsider.in', 
    message: "#{File.basename(lane_context[SharedValues::IPA_OUTPUT_PATH], '.ipa')} is ready to test.",
    keep_same_link: true,
  )
end

desc "Upload IPA file and keep the same link for all future upload IPAs in Custom Dropbox folder."
lane :testCustomDBFolderName do
  gym
  appbox(
    emails:'info@developerinsider.in', 
    message: "#{File.basename(lane_context[SharedValues::IPA_OUTPUT_PATH], '.ipa')} is ready to test.",
    keep_same_link: true,
    dropbox_folder_name: 'Fastlane-Demo-Keep-Same-Link',
  )
end